spring:
  application:
    name: html2md
  main:
    banner-mode: off

app:
  logging:
    pattern:
      normal: "%m%n"
      #debug: "%clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(---){faint} %clr(${LOG_CORRELATION_PATTERN:-}){faint}%clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"
      debug: "%clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(---){faint} %clr(${LOG_CORRELATION_PATTERN:-}){faint}%clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"

logging:
  include-application-name: false
  level:
    root: error
    org.carth: error
    #pattern:
    #console: "-%clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(---){faint} %clr(${LOG_CORRELATION_PATTERN:-}){faint}%clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
  #  console: "%m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}"
