spring:
  application:
    name: html2md
  main:
    banner-mode: off

logging:
  include-application-name: false
  level:
    org.carth: debug
  pattern:
    console: -%clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(---){faint} %clr(${LOG_CORRELATION_PATTERN:-}){faint}%clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}
